### ISSUE TITLE
Doesn't load on IDA 9.0

### ISSUE THREAD

**Issue by Armandukx** [herosi/classinformer#9]
![image](https://github.com/user-attachments/assets/1b985836-63bd-4bec-93e3-480e7093d12a)

**Comment by herosi** [comment]
What version do you use? I checked on 9.0.240925.
If you use a beta version of IDA 9.0, you will need to use the binary below because a beta version uses different IDA's DLL from the released version.
https://github.com/rohitab/ClassInformer/releases/tag/v2.9

**Comment by herosi** [comment]
I could not reproduce it on my environment. And there is no information except for an error message.

**Comment by herosi** [comment]
You should give the information in detail if you want to resolve the issue.
